### ISSUE TITLE
Projekt - zaliczenie etapów 1  i 2

### ISSUE THREAD

**Issue by MagdaMlynarczyk** [pbiecek/LinearModels#196]
Dzień dobry,

pliki w folderze:
https://github.com/pbiecek/LinearModels/tree/master/MIMUW_2017/Projekty/A.Dabrowska-%20J.Dmitruk-%20M.Mlynaryczyk

Pozdrawiam

**Comment by pbiecek** [comment]
Oba punkty zaliczone,
ale na przyszłość:
- wykresy diagnostyczne można było zrobić w ggplot2
- podpunkty proszę numerować, 1.1, 1.2 itp, teraz trudno się odnieść do któregoś podpunktu
- wykres 'Boxploty dla zadań z podziałem na pozycję zadania' jest wybietnie nieczytelny. Dlaczego czas jest w milisekundach a nie sekundach czy minutach? Zamiast całych boxplotów mozna by pokazać średnie, bo teraz niewiele można odczytać
- tytuły rozdziałów powinny mówić coś o treści. Tytuł typu 'Wykresy dla danych' niewiele wnosi. 
- na zajęciach rozmawialiśmy o tym, że umieszczanie wyrazu wolnego na wykresie 'Wizualizacja modelu' nie ma sensu
- w podsumowaniu jest informacja, które zmienne trafiły do modelu, ale nie ma informacji jak wygląda ten końcowy model.
