### ISSUE TITLE
Projekt - zaliczenie etapów 1 i 2

### ISSUE THREAD

**Issue by DawidDabkowski** [pbiecek/LinearModels#197]
Plik Projekt_1-2.html oraz Projekt_1-2.rmd

Etapy 1 i 2

Anna Wójcik, Grzegorz Ziajka, Dawid Dąbkowski

**Comment by pbiecek** [comment]
Zaliczone etapy 1-2,
ale na przyszłość:
- diagnostyka jest zrobiona, ale np. dla jednorodności wariancji jedyny komentarz to 'Werdykt negatywny.' Trochę mało.
- brakuje wizualizacji modelu, jest wizualizacja reszta i diagnostyki, ale jeżeli wybrany model to 'sqrt(T)~position+M/Q.' gdzie znajdę prezentację graficzną składników tego modelu? (np. bet)
- bardzo przydałby się spis treści (generuje go knitr automatycznie) i numeracja podrozdziałów (1.1, 1.2 itp)

Drobne:
'boxa-coxa' - to nazwiska, powinny być z dużej litery
