### ISSUE TITLE
Piotr Bajger - Etap II

### ISSUE THREAD

**Issue by piotrbajger** [pbiecek/LinearModels#232]
Etap 2. projektu -- będę wdzięczny za ocenienie.

(Etapy 3. i 4. też gotowe, chciałbym jedynie uwzględnić ew. feedback po Etapie 2.)

**Comment by piotrbajger** [comment]
Dodane Etapy 3. i 4. (jeśli 2. zostanie zaliczony).

**Comment by pbiecek** [comment]
Największą wadą 2 etapu jest zbiór stwierdzeń _'Model nie przechodzi testu XYZ'_ bez komentarza co dalej.
Spodziewałbym się conajmniej reakcji w postaci zaproponowania innego ,,lepszego'' modelu lub uzasadnienia, dlaczego pomimo takich wyników diagnostycznych można wciąż korzystać z gaussowskich modeli liniowych.

**Comment by pbiecek** [comment]
Etapy 3-4 to jedne z ostatnich zgłoszonych rozwiązań. Przed nimi zgłoszono wiele innych rozwiązań tych i kolejnych etapów, można było sprawdzić co w tych innych rozwiązaniach sprawdziło się a co nie. Taka praca nie została wykonana, więc w tych etapach powielane są błędy, początkowo zgłaszane przez inne zespoły:

- jest zbiór różnych wykresów bez żadnego komentarza co z nich wynika. Przykładowo, jest różnica średnich w czasach w zależności czy w domu są 'art books'. Jeżeli są to czasy są dłuższe. Ale jaki jest komentarz do tej zależności? 
- wykresy są niedopracowane, przez co trudno cokolwiek z nich wywnioskować. PRzykładowo, w rozdziale _'3.2.2 Książki i instrumenty muzyczne'_ dla instrumentów muzycznych średnie są ułożone w kolejności rosnącej, ale znacznie sensowniejsze byłoby zagwarantowanie by poziomy na osi OX były w kolejności rosnącej (None, One, Two, 3+). Tylko to pozwoliłoby na określenie czy istnieje jakaś monotoniczna zależność. Podobnie z ISCED.
- Wykresy są powtarzane w konfiguracji średnia +- se a później rozkład. Pytanie co wnosi dodatkowego takie dublowanie wykresów. Na wykresie z boxplotami zazwyczaj trudno dotrzeć jakikolwiek trend w średnich. 
- W przypadku wykresu dla interakcji pozycji i numeru zadania (ostatni wykres) nie wiem co wynika z porównania efektów zadania dla ustalonych pozycji. Potrafię sobie wyobrazić odwrotną sytuację, gdzie panele odpowiadają numerom zadań a wewnątrz panelu znajdują się wyniki dla kolejnych pozycji - wtedy można by odczytać jako określone zadanie 'pracuje' na kolejnych pozycjach i czy rzeczywiście dla każdego zadania z pozycją skraca się czas rozwiązania. Ale obecnie nie wiem co z tego wykresu można odczytać.

Etap 2 i 3 jest zaliczony, ale etap 4 nie. Wizualizacja modelu w zadaniu 4 wymaga by istniał jeden model, który jest poprawny (w sensie diagnostyki) i z które wynika co i jak wpływa na czas rozwiązywania zadań.
